
global has_motor: bool;
global has_repaired_motor: bool;

global has_well_part_map: bool;
global has_pump_gear: bool;
global has_repaired_pump: bool;

global has_generator_part_map: bool;
global has_generator_part_0: bool;
global has_generator_part_1: bool;
global has_generator_part_2: bool;
global has_repaired_generator: bool;

global has_health_juice_map: bool;
global has_health_juice: bool;
global has_repaired_health_machine: bool;

global scrapbot_location: i8;
global samson_location: i8;